feat (#58): common component replaced button
timemates/app pull request #71
Opened 2023-07-29 15:15 UTC by 1Rinkana

closes #58

2023-07-29 17:12 UTC, y9vad9 approved these changes

2023-07-29 17:16 UTC, sliderzxc requested changes
add trailing comma

2023-07-29 17:16 UTC, y9vad9 requested changes

2023-07-29 17:16 UTC, y9vad9 commented on style-system/src/commonMain/kotlin/io/timemates/app/style/system/button/Button.kt
> +    androidx.compose.material3.Button(
зареюзай будь-ласка Button наш

2023-07-29 21:15 UTC, y9vad9 approved these changes

2023-07-30 12:48 UTC, sliderzxc approved these changes

2023-07-30 12:51 UTC, merged