feat (#59): UsersRepository implementation
timemates/app pull request #87
Opened 2023-07-31 17:43 UTC by kotleni

**Is it breaking change?**
No.

**Specify linked issues or discussions**

Close #59 

**Additional information**

Implemented `UsersRepository`, `CachedUsersDataSource` and `CachedUsers` sql. 
Changed in `UserRepositoryContract` methods getUser and getUsers for using with flows.

Now, if repository have cache - this data will be emited to flow first. 
And after - the data will be loaded from the SDK and will also be emited and updated in cache.

2023-07-31 18:09 UTC, y9vad9 requested changes

2023-07-31 18:09 UTC, y9vad9 commented on feature/users/data/src/commonMain/kotlin/io/timemates/app/users/data/CachedUsersDataSource.kt
> +        CoroutineScope(Dispatchers.Default).launch {
зміни або на GlobalScope, або передавай CoroutineScope через конструктор

2023-07-31 18:09 UTC, y9vad9 commented on feature/users/data/src/commonMain/kotlin/io/timemates/app/users/data/CachedUsersDataSource.kt
> +        CoroutineScope(Dispatchers.Default).launch {
також, я думаю, що має клірити відповідно до часу, наприклад кеш актуальний 5 хв.

2023-07-31 18:09 UTC, y9vad9 commented on feature/users/data/src/commonMain/kotlin/io/timemates/app/users/data/UsersRepository.kt
> +        // Emit local saved data (is have)
```suggestion
        // Emit local saved data (if have)
```

2023-07-31 18:09 UTC, y9vad9 commented on feature/users/data/src/commonMain/kotlin/io/timemates/app/users/data/CachedUsersDataSource.kt
> +        CoroutineScope(Dispatchers.Default).launch {
```suggestion
        GlobalScope.launch(Dispatchers.Default) {
```

2023-08-01 13:31 UTC, y9vad9 commented on feature/users/data/src/commonMain/kotlin/io/timemates/app/users/data/CachedUsersDataSource.kt
> +    private suspend fun clear() = withContext(Dispatchers.IO) {
I think we still should clear cache by time, not by creating it. User can close the app and reopen it much faster. I think cache should serve ~10 minutes.

2023-08-01 14:41 UTC, 1Rinkana approved these changes

2023-08-07 02:49 UTC, merged