feat(#89) initial authorization screen created
timemates/app pull request #94
Opened 2023-08-10 18:06 UTC by 1Rinkana

Added InitialAuthorization(screen, reducer, state machine, also added a few lines to LocalStrings and secondaryVariant color to AppTheme colors).

Changed the home screen in the navigation to InitialAuthorizationScreen.

close #89

2023-08-10 21:12 UTC, kotleni requested changes
Чому картинка дублюється в common та desktop?

2023-08-10 21:15 UTC, kotleni approved these changes

2023-08-11 00:27 UTC, y9vad9 approved these changes
good job

2023-08-11 00:31 UTC, y9vad9 requested changes
add navigation

2023-08-11 00:55 UTC, y9slavabogu approved these changes

2023-08-11 00:55 UTC, y9vad9 approved these changes

2023-08-11 08:51 UTC, sliderzxc approved these changes

2023-08-11 11:37 UTC, merged